/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistas;

import com.joseluu.proyectofinalmongojavi.controlador.DatabaseManager;
import com.joseluu.proyectofinalmongojavi.entidad.Continente;
import com.joseluu.proyectofinalmongojavi.entidad.Pais;
import javax.swing.JOptionPane;

/**
 *
 * @author Montero
 */
public class Paises extends javax.swing.JDialog {

    DatabaseManager managerDatabase;

    /**
     * Creates new form Paises
     */
    public Paises(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        managerDatabase = new DatabaseManager();
        this.inicializarComboBoxContinente();
        this.inicializarComboBoxPaises();
    }

    public void inicializarComboBoxContinente() {

        managerDatabase.runMongoDatabase();
        comboBoxContinentes.removeAllItems();
        managerDatabase.getListaDeContinentes()
                .forEach(c -> comboBoxContinentes.addItem(c.getName()));

        managerDatabase.closeMongoDatabase();
    }

    public void inicializarComboBoxPaises() {
        managerDatabase.runMongoDatabase();
        comboBoxPaises.removeAllItems();
        managerDatabase.getListaPaises()
                .forEach(p -> comboBoxPaises.addItem(p.getNombrePais()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTextNumHabitantes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAñadirPais = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        comboBoxPaises = new javax.swing.JComboBox<>();
        inputTextNombrePais = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxContinentes = new javax.swing.JComboBox<>();
        btnEliminarPais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Añadir paises");

        btnAñadirPais.setText("Añadir Pais");
        btnAñadirPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPaisActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboBoxPaises.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("N Habitantes");

        jLabel3.setText("Nombre Pais");

        jLabel4.setText("Eliminar Pais");

        comboBoxContinentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEliminarPais.setText("Eliminar Pais");
        btnEliminarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxPaises, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(inputTextNombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxContinentes, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputTextNumHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(btnAñadirPais, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAñadirPais, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(comboBoxContinentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTextNumHabitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTextNombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPaisActionPerformed
        try {
            String nombrePais = inputTextNombrePais.getText();
            int numeroHabitantes = Integer.parseInt(inputTextNumHabitantes.getText());
            String nombreContinente = (String) comboBoxContinentes.getSelectedItem();

            if (managerDatabase.runMongoDatabase()) {

                Continente continente = managerDatabase.getListaDeContinentes()
                        .stream()
                        .filter(c -> c.getName().equalsIgnoreCase(nombreContinente))
                        .findFirst()
                        .orElse(null);

                if (continente != null) {

                    if (nombrePais.contains(" ") || inputTextNumHabitantes.getText().contains(" ")) {
                        JOptionPane.showMessageDialog(this, "Has añadido espacios no validos quitalos");
                    } else {

                        boolean existe = managerDatabase.getListaPaises().stream()
                                .anyMatch(c -> c.getNombrePais().equalsIgnoreCase(nombrePais));

                        if (!existe) {

                            String continenteId = managerDatabase.getIdFromContinente(nombreContinente);

                            Pais pais = new Pais(numeroHabitantes, nombrePais, continenteId);

                            managerDatabase.añadirPais(pais);
                            this.inicializarComboBoxPaises();

                        } else {
                            JOptionPane.showMessageDialog(this, "Has añadido uno ya existente");
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el continente.");
                }

                managerDatabase.closeMongoDatabase();

            } else {
                JOptionPane.showMessageDialog(this, "Error con la database");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: El campo número de habitantes solo acepta números.");
        }
    }//GEN-LAST:event_btnAñadirPaisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPaisActionPerformed
        String nombrePais = (String) comboBoxPaises.getSelectedItem();

        if (managerDatabase.runMongoDatabase()) {

            // Buscar paises por nombre
            Pais pais = managerDatabase.getListaPaises()
                    .stream()
                    .filter(p -> p.getNombrePais().equalsIgnoreCase(nombrePais))
                    .findFirst()
                    .orElse(null);

            if (pais != null) {
                managerDatabase.deletePais(pais);
                this.inicializarComboBoxPaises();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el continente.");
            }

            managerDatabase.closeMongoDatabase();

        } else {
            JOptionPane.showMessageDialog(this, "Error con la database");
        }
    }//GEN-LAST:event_btnEliminarPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Paises dialog = new Paises(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirPais;
    private javax.swing.JButton btnEliminarPais;
    private javax.swing.JComboBox<String> comboBoxContinentes;
    private javax.swing.JComboBox<String> comboBoxPaises;
    private javax.swing.JTextField inputTextNombrePais;
    private javax.swing.JTextField inputTextNumHabitantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
